### ISSUE TITLE
Finish rollout of new FY17 travel policies

### ISSUE THREAD

**Issue by ethanheppner** [18F/ops-improvements#1]
Comms staged [here](https://docs.google.com/document/d/1IEZ1m1zpGpXW8FKiTIkESQRcXu0diEp7AV7L87zyQdA/edit?pli=1)

- [x] #1. Travel office hours
- [x] #2. New nonbillable travel policy
- [x] #3. New billable travel policy
- [x] #4. Don't worry about accounting codes anymore -- [Pull request](https://github.com/18F/handbook/pull/100) and [Comms](https://docs.google.com/document/d/1p_S8p-5u2AySb6jGdCOoIMwx1ACkyu-uh79ta3CAzSs/edit)
- [x] #5. Policy on nonrefundable flights and hotels -- [Comms](https://docs.google.com/document/d/1GH2OxttJDJwbGFkdfArI67vRjWmwyGNSj8CMyYiIuFA/edit)
- [x] #6. Submit all vouchers within 5 days of return -- [Pull request](https://github.com/18F/handbook/pull/119) and [Comms](https://docs.google.com/document/d/19h73I9j-a85cNj50htmLfXND8GHG688Dtd19jZ2nkdA/edit)
